dustpath/web/views/accounts.py
from flask import Blueprint, render_template, url_for, redirect, request
from flask_login import login_user, logout_user, login_required, current_user
from dustpath import models
from dustpath.web import forms
from dustpath.web import oauth2


module = Blueprint("accounts", __name__)

@module.route("/login", methods=("GET", "POST"))
def login():
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.index"))
    return render_template("/accounts/login.html")


@module.route("/login/<name>")
def login_oauth(name):
    client = oauth2.oauth2_client
    redirect_uri = url_for("accounts.authorized_oauth", name=name, _external=True)
    response = None
    if name == "google":
        response = client.google.authorize_redirect(redirect_uri)
    elif name == "facebook":
        response = client.facebook.authorize_redirect(redirect_uri)
    return response


@module.route("/auth/<name>")
def authorized_oauth(name):
    client = oauth2.oauth2_client
    remote = None
    try:

        if name == "google":
            remote = client.google
        elif name == "facebook":
            remote = client.facebook

        token = remote.authorize_access_token()

    except Exception as e:
        print(e)
        return redirect(url_for("accounts.login"))

    return oauth2.handle_authorized_oauth2(remote, token)


@module.route("/update_last_project_view")
@login_required
def update_last_project_view():
    project_id = request.args.get("project", default="")
    user = current_user._get_current_object()
    if project_id:
        project_selected = models.Project.objects(id=project_id).first()
        user.last_project_view = project_selected
        current_user.save()
    return redirect(url_for("dashboard.index"))


@module.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))

dustpath/web/views/domains.py
from dustpath.models import domains
from flask import (Blueprint,
                   render_template,
                   redirect,
                   url_for,
                   request,
                   jsonify
                   )
import json, datetime
from flask_login import login_required
from .. import models

module = Blueprint('domains', __name__, url_prefix='/domains')

@module.route('/')
@login_required
def index():
    domains = models.Domain.objects().order_by("-id")
    return render_template('domains/index.html',
                            domains=domains,)

@module.route('/record', methods=['GET', 'POST'])
@login_required
def record():
    center = [7.0065949668769205, 100.49891880632555] # lat, long
    zoom = 10
    
    if request.method == 'POST':
        data = request.json
        if data:
            domain = models.Domain(
                name=data['name'],
                center=data['center'],
                width=data['width'],
                hight=data['hight'],
                dx=data['width']/100,
                dy=data['hight']/100,
                e_we=100,
                e_sn=100,
                )
            area = (domain.dx / 1000) * (domain.dy / 1000) * 10000
            if domain.dx < domain.dy:
                domain.dy = domain.dx
                resolution = (domain.dx / 1000) * (domain.dy / 1000)
                domain.e_sn = (area / resolution) / 100
            elif domain.dy < domain.dx:
                domain.dx = domain.dy
                resolution = (domain.dx / 1000) * (domain.dy / 1000)
                domain.e_we = (area / resolution) / 100
            domain.save()
    return render_template('domains/record.html',
                           zoom=zoom,
                           center=center,)

dustpath/web/views/projects.py
import pwd
from dustpath.models import projects
from flask import (
    Blueprint,
    render_template,
    redirect,
    request,
    url_for,
    Response,
    g,
    current_app,
    jsonify,
)
import datetime
from flask_login import login_required, current_user
import json
import pathlib
import pandas
from dustpath import models
from dustpath.web import nats

from ..forms import ProjectForm

from .. import forms

module = Blueprint("projects", __name__, url_prefix="/projects")

@module.route('/')
@login_required
def index():
    projects = models.Project.objects().order_by("-id")
    return render_template('projects/index.html',
                            projects=projects,)

@module.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = ProjectForm()
    form.domain.choices = get_domains_choices()
    if not form.validate_on_submit():
        return render_template('projects/create.html', form=form)
    project = models.Project(
        name=form.name.data,
        output_filename=f"wrfout_d01_{form.start_date.data}_00:00:00",
    )
    project.wrf_config.start_date = form.start_date.data
    project.wrf_config.end_date = form.end_date.data

    domain = models.Domain.objects.get(id=form.domain.data)
    project.wrf_config.domain = domain
    project.save()
    return redirect(url_for('projects.index'))
    
@module.route("/<project_id>/run_wrf", methods=["GET", "POST"])
@login_required
def run_wrf(project_id):
    project = models.Project.objects.get(id=project_id)

    data = {
        "action": "start",
        # "user_id": str(current_user._get_current_object().id),
        "attributes": {
            "project_id": project_id,
            },
    }
    nats.nats_client.publish("dustpath.processor.command", data)
    
    return redirect(url_for('projects.result', project_id=project_id))

@module.route('<project_id>/result', methods=['GET','POST'])
@login_required
def result(project_id):
    project = models.Project.objects.get(id=project_id)
    try:
        filename = pathlib.Path(f'dustpath/web/static/projects/{project_id}/PM2_5_ALL.csv')
        file = pandas.read_csv(filename, header=0) 
        data = file.values
        if len(data) == 0:
            data = None
    except Exception as e:
        print(e)
        data = None
    return render_template('projects/result.html',
        project_id=project_id, 
        result=result, 
        project=project,
        data=data,
        )

def get_domains_choices():
    domains = models.Domain.objects()
    return [(str(d.id), f"{d.name}") for d in domains]

dustpath/web/templates/base/base-layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" media="all"
    href="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.css') | add_date_url }}">

  <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') | add_date_url }}"></script>
  <script
    src="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.js') | add_date_url }}"></script>

  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') | add_date_url }}">
  <link rel="icon" href="{{ url_for('static', filename='images/icon.png') | add_date_url }}">
  <script src="{{ url_for('static', filename='node_modules/brython/brython.js') | add_date_url }}"></script>
  <script src="{{ url_for('static', filename='node_modules/brython/brython_stdlib.js') | add_date_url }}"></script>
  {% block additional_head %}{% endblock %}

  <title>{% block title %}{{ config.get('APP_TITLE') }}{% endblock %}</title>
</head>

<body onload="brython()">
  {% block body %}{% endblock %}
</body>
{% block additional_js %}{% endblock %}
{% include "base/footer.html" %}

<script>
  $('.ui.dropdown')
    .dropdown();
  $(document)
    .ready(function () {
      $('.left.sidebar.menu')
        .sidebar('attach events', '.launch.icon.item', 'show')
        ;
    })
    ;
</script>

</html>

dustpath/web/templates/base/base-map.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <style>
        #mapid { 
            height: 60rem;
            background-color:white;
        }
        #back_btt{
            position: absolute; 
            margin: 9px;
            padding: 10px;
            width: 80px; 
            background-color: #ffffff; 
            border-radius: 10%;
            font-size: 30px; 
            text-align: center; 
            z-index: 10;
          }
    </style>
    <title>{% block title  %}{{ config.get('APP_TITLE') }}{% endblock %}</title>
    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.css') }}">
    <script src="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/brython/brython.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/brython/brython_stdlib.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/leaflet/dist/leaflet.css') }}" />
    <script src="{{ url_for('static', filename='node_modules/leaflet/dist/leaflet.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/leaflet-draw/dist/leaflet.draw.css') }}" />
    <script src="{{ url_for('static', filename='node_modules/leaflet-draw/dist/leaflet.draw.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/leaflet-geometryutil/src/leaflet.geometryutil.js') }}"></script>
    <link rel="icon" href="{{ url_for('static', filename='images/icon.png') | add_date_url }}">
</head>

<body onload="brython()">
    {% block body %}{% endblock %}
</body>
</html>

dustpath/web/templates/base/default-page.html
{% extends "base/base-layout.html" %}

{% block body %}

  {% include "base/navbar.html" %}
  {% include "base/sidebar.html" %}


  <main class="ui vertical segment">
    {% block content %}{% endblock content %}
  </main>
{% endblock %}

dustpath/web/templates/base/footer.html
<footer class="ui inverted vertical segment">
  <div class="ui container">
    <div class="ui two column stackable grid">
      <div class="column">
        <h4>
          เกี่ยวกับ
        </h4>
        <div>
          <img src="{{ url_for('static', filename='images/icon.png') }}" class="center"
            style="width:105px; height:115px; margin-bottom: 1rem;">
          <br>Dustpath<br>ระบบจำลองการเคลื่อนตัวของฝุ่น PM 2.5
        </div>
      </div>
      {#
      <div class="column">
        <h4>
          ผู้จัดทำ
        </h4>
        1. นายพงศธร ชดช้อย<br>2. นายทิวัตถ์ ลิม<br>3. นายธีรยุทธ นุชผดุง
        <h4>
          อาจารย์ที่ปรึกษาโครงการ
        </h4>
        <div>
          ดร.ธนาธิป ลิ่มนา
        </div>
      </div>
      #}
      <div class="column">
        <h4>
          สนับสนุนโดย
        </h4>
        <div class="inverted link list">
          <a href="http://www.coe.psu.ac.th" class="item">
            <img src="/static/images/coe-psu-branding-white.png"  style="width:329px; height:64px;">
          </a>
          <a href="http://air.psu.ac.th/" class="item">
            <img src="/static/images/anh.png" style="width:140px; height:90px;">
          </a>
          <img src="/static/images/r202-white.png" class="ui tiny centered image">
        </div>
      </div>
    </div>
  </div>
</footer>

dustpath/web/templates/base/navbar.html
<style>
    .ui.fixed.borderless.menu {
        background-color: #44545C;
    }

    span.title_text {
        font-weight: lighter;
    }

    .white {
        color: #ffffff;
    }
</style>
<div class="ui borderless menu fixed" style="position: fixed; top: 0px; left: auto; z-index: 10; box-shadow: none;">
    <a class="launch icon item">
        <i class="white sidebar icon"></i>
    </a>
    <div class="header item">
        <a href="{{ url_for('dashboard.index') }}" style="text-decoration: none;">
            <h1 class="title_text white">
                {{ config['APP_TITLE'] }}
            </h1>
        </a>
    </div>
    <div class="right menu">
        <a href="{{ url_for('accounts.logout') }}" class="ui item" >
            <span class="white">
                Logout
            </span>
        </a>
    </div>
</div>

dustpath/web/templates/base/sidebar.html
  <div class="ui vertical inverted sidebar large menu left">
    <div class="item">
      <span style="font-size: 24px">{{ config['APP_TITLE'] }}</span>
    </div>
    <div class="item">
      <a href="{{ url_for('dashboard.index') }}" class="header" style="text-decoration: none;">
        <i class="home icon"></i>
        Dashboard
      </a>
    </div>
    <div class="item">
      <a class="header" style="text-decoration: none;">
        <i class="map icon"></i>
        Domain
      </a>
      <div class="menu">
        <a href="{{ url_for('domains.record') }}" class="item">
          <i class="map marker alternate icon"></i>Create
        </a>
        <a href="{{ url_for('domains.index') }}" class="item">
          <i class="map icon"></i>Domains
        </a>
      </div>
    </div>
    <div class="item">
      <a class="header" style="text-decoration: none;">
        <i class="archive icon"></i>
        Project
      </a>
      <div class="menu">
        <a href="{{ url_for('projects.create') }}" class="item">
          <i class="file icon"></i>Create
        </a>
        <a href="{{url_for('projects.index')}}" class="item">
          <i class="folder alternate icon"></i>Projects
        </a>
      </div>
    </div>
    {#
    <div class="item">
      <a href="{{ url_for('users.record') }}" class="header" style="text-decoration: none;">
        <i class="user icon"></i>
        โปรไฟล์
      </a>
    </div>
    #}
  </div>